# Site settings
author: Ryan Whitney
title: Ryan's Coding Journey
header-img: img/home-bg.png
email: whitney.ryan.a@gmail.com
copyright_name: Ryan Whitney
description: > # this means to ignore newlines until "baseurl:"
  The story of packing up and moving outside my comfort zone.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  pnwhiker

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
